# Generated by Django 4.2.9 on 2024-05-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('UC', models.IntegerField(blank=True, null=True)),
                ('HC', models.IntegerField(blank=True, null=True)),
                ('ISC', models.IntegerField(blank=True, null=True)),
                ('SCC', models.IntegerField(blank=True, null=True)),
                ('SRC', models.IntegerField(blank=True, null=True)),
                ('SRB', models.IntegerField(blank=True, null=True)),
                ('SRC_UV', models.IntegerField(blank=True, null=True)),
                ('SRBUV', models.IntegerField(blank=True, null=True)),
                ('RCC', models.IntegerField(blank=True, null=True)),
                ('HSC', models.CharField(blank=True, max_length=100, null=True)),
                ('SUNHC', models.IntegerField(blank=True, null=True)),
                ('SUNSCC', models.IntegerField(blank=True, null=True)),
                ('SUNUC', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
