# Generated by Django 4.2.9 on 2024-05-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0002_alter_exceldata_hc_alter_exceldata_isc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='SRC_UV',
            new_name='SRCUV',
        ),
    ]
