# Generated by Django 4.2.9 on 2024-05-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0003_rename_src_uv_exceldata_srcuv'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='POLA_ISC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='POLA_UC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
