# Generated by Django 4.2.9 on 2024-05-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0004_exceldata_pola_isc_exceldata_pola_uc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='price',
            new_name='prix',
        ),
    ]
