# Generated by Django 4.2.9 on 2024-05-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0005_rename_price_exceldata_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exceldata',
            name='classeur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comparateur.classeur'),
        ),
    ]
