# Generated by Django 4.2.9 on 2024-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0007_exceldata_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='remise',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
