# Generated by Django 4.2.9 on 2024-05-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0008_alter_exceldata_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
