# Generated by Django 4.2.9 on 2024-05-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0012_alter_exceldata_hc_alter_exceldata_hsc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ophtal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('prix_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_net', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
