# Generated by Django 4.2.9 on 2024-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0013_ophtal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='classeur',
        ),
    ]
