# Generated by Django 4.2.9 on 2024-05-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0014_remove_exceldata_classeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seiko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('UC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('HC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ISC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SCC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SRC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SRB', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SRCUV', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SRBUV', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('RCC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('HSC', models.CharField(default='', max_length=100)),
                ('SUNHC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SUNSCC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SUNUC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('POLA_UC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('POLA_ISC', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StarVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelData',
        ),
    ]
