# Generated by Django 4.2.9 on 2024-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0015_seiko_starvision_delete_exceldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seiko',
            name='HSC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
