# Generated by Django 4.2.9 on 2024-05-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0016_alter_seiko_hsc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seiko',
            old_name='HSC',
            new_name='SUNISC',
        ),
        migrations.RemoveField(
            model_name='seiko',
            name='SUNSCC',
        ),
    ]
