# Generated by Django 4.2.9 on 2024-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0018_starvision_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='seiko',
            name='date_debut_remise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seiko',
            name='date_fin_remise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starvision',
            name='date_debut_remise',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starvision',
            name='date_fin_remise',
            field=models.DateField(blank=True, null=True),
        ),
    ]
