# Generated by Django 4.2.9 on 2024-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0020_seiko_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classeur_Name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('SANS_TR', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('DIAPLUS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MAJOR_CLEAN', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('SELIS_XT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('GRAPHENE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('AIRLIS_Shock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('BLUE_Shock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
