# Generated by Django 4.2.9 on 2024-06-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0021_novacell'),
    ]

    operations = [
        migrations.AddField(
            model_name='novacell',
            name='BLANC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='novacell',
            name='TEINTE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
