# Generated by Django 4.2.9 on 2024-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparateur', '0022_novacell_blanc_novacell_teinte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKSESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('PRIX', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='POL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('DIAPLUS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ARINTERNE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MAJOR', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('AIRLIS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='novacell',
            old_name='AIRLIS_Shock',
            new_name='AIRLISShock',
        ),
        migrations.RenameField(
            model_name='novacell',
            old_name='BLANC',
            new_name='GRAPHEN',
        ),
        migrations.RenameField(
            model_name='novacell',
            old_name='GRAPHENE',
            new_name='MAJOR',
        ),
        migrations.RenameField(
            model_name='novacell',
            old_name='MAJOR_CLEAN',
            new_name='SANSTR',
        ),
        migrations.RenameField(
            model_name='novacell',
            old_name='SANS_TR',
            new_name='SELISXT',
        ),
        migrations.RemoveField(
            model_name='novacell',
            name='Classeur_Name',
        ),
        migrations.RemoveField(
            model_name='novacell',
            name='SELIS_XT',
        ),
        migrations.RemoveField(
            model_name='novacell',
            name='TEINTE',
        ),
    ]
