# Generated by Django 5.0.1 on 2024-01-18 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avoirapp', '0005_famille_avoir_famille'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bon_Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere_d', models.FloatField()),
                ('cylindre_d', models.FloatField()),
                ('axe_d', models.FloatField()),
                ('quatite_d', models.IntegerField()),
                ('sphere_g', models.FloatField()),
                ('cylindre_g', models.FloatField()),
                ('axe_g', models.FloatField()),
                ('quatite_g', models.IntegerField()),
                ('categorie_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_d', to='avoirapp.famille')),
                ('categorie_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_g', to='avoirapp.famille')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avoirapp.client')),
                ('produit_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_d', to='bl_app.produit')),
                ('produit_g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_g', to='bl_app.produit')),
            ],
        ),
    ]
