# Generated by Django 5.0.1 on 2024-01-18 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon_commande',
            name='date_de_bl',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
