# Generated by Django 5.0.1 on 2024-01-17 10:08

import avoirapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('datenaissance', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('facture', models.FileField(upload_to=avoirapp.models.upload_invoice_path)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avoirapp.client')),
            ],
        ),
    ]
