# Generated by Django 5.0.1 on 2024-01-17 10:11

import avoirapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='facture',
            field=models.FileField(upload_to=avoirapp.models.upload_invoice_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
