# Generated by Django 5.0.1 on 2024-01-17 12:19

import avoirapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0002_alter_avoir_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='is_avoir',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='facture',
            field=models.FileField(null=True, upload_to=avoirapp.models.upload_invoice_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
