# Generated by Django 5.0.1 on 2024-01-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0003_avoir_is_avoir_alter_avoir_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='ean_13',
            field=models.CharField(max_length=13, null=True, verbose_name='EAN-13 Barcode'),
        ),
    ]
