# Generated by Django 5.0.1 on 2024-01-18 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0004_avoir_ean_13'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='avoir',
            name='famille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avoirapp.famille'),
        ),
    ]
