# Generated by Django 5.0.1 on 2024-02-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avoirapp", "0005_famille_avoir_famille"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="telephone",
        ),
    ]
