# Generated by Django 5.0.1 on 2024-02-29 00:38

import avoirapp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avoirapp", "0006_remove_client_email_remove_client_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avoir",
            name="description",
        ),
        migrations.RemoveField(
            model_name="avoir",
            name="ean_13",
        ),
        migrations.RemoveField(
            model_name="avoir",
            name="famille",
        ),
        migrations.RemoveField(
            model_name="avoir",
            name="is_avoir",
        ),
        migrations.AlterField(
            model_name="avoir",
            name="facture",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=avoirapp.models.upload_invoice_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Consommation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prix_achat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_vente", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_ajout", models.DateField(auto_now_add=True)),
                ("designation", models.TextField()),
                (
                    "code_barre",
                    models.CharField(
                        max_length=13, null=True, verbose_name="EAN-13 Barcode"
                    ),
                ),
                (
                    "facture",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=avoirapp.models.upload_invoice_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="avoirapp.client",
                    ),
                ),
                (
                    "famille",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="avoirapp.famille",
                    ),
                ),
            ],
        ),
    ]
