# Generated by Django 5.0.1 on 2024-03-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avoirapp", "0007_remove_avoir_description_remove_avoir_ean_13_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="famille",
            name="is_facture",
            field=models.BooleanField(default=True),
        ),
    ]
