# Generated by Django 5.0.1 on 2024-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avoirapp", "0008_famille_is_facture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="famille",
            name="is_facture",
            field=models.BooleanField(default=False),
        ),
    ]
