# Generated by Django 4.2.9 on 2024-03-02 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0011_alter_consommation_code_barre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
