# Generated by Django 4.2.9 on 2024-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0012_alter_avoir_date_ajout_alter_consommation_date_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
