# Generated by Django 4.2.9 on 2024-03-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0013_famille_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='is_barre',
            field=models.BooleanField(default=True),
        ),
    ]
