# Generated by Django 4.2.9 on 2024-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0014_famille_is_barre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='famille',
            name='is_barre',
            field=models.BooleanField(default=False),
        ),
    ]
