# Generated by Django 4.2.9 on 2024-03-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0015_alter_famille_is_active_alter_famille_is_barre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='DEFAULT_VALUE', editable=False, max_length=20, unique=True)),
                ('mois_concerne', models.CharField(max_length=7, unique=True)),
            ],
        ),
    ]
