# Generated by Django 4.2.9 on 2024-03-08 19:29

import avoirapp.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0017_repertoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('facture', models.FileField(blank=True, null=True, upload_to=avoirapp.models.upload_invoice_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
