# Generated by Django 4.2.9 on 2024-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0018_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retour',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
