# Generated by Django 4.2.9 on 2024-03-08 21:02

import avoirapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0019_alter_retour_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retour',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to=avoirapp.models.upload_invoice_path_retour, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
