# Generated by Django 4.2.9 on 2024-03-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0020_alter_retour_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='code_barre',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
