# Generated by Django 4.2.9 on 2024-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0021_alter_consommation_code_barre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='code_barre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
