# Generated by Django 4.2.9 on 2024-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0022_alter_consommation_code_barre'),
    ]

    operations = [
        migrations.AddField(
            model_name='retour',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='identifiant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='mot_de_passe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='site_internet',
            field=models.URLField(blank=True, null=True),
        ),
    ]
