# Generated by Django 4.2.9 on 2024-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0023_retour_marque_alter_repertoire_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retour',
            name='marque',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
