# Generated by Django 4.2.9 on 2024-03-24 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0026_alter_retour_marque_vente_journeevente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeevente',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
