# Generated by Django 4.2.9 on 2024-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0027_alter_journeevente_date_alter_vente_date_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeevente',
            name='ca_jour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='journeevente',
            name='ca_jour_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
