# Generated by Django 4.2.9 on 2024-03-29 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0029_teletransmition_stock_sav_remisebanque_livraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teletransmition',
            name='vente',
        ),
    ]
