# Generated by Django 4.2.9 on 2024-03-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0030_remove_teletransmition_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeevente',
            name='ca_mois',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='journeevente',
            name='ca_mois_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
