# Generated by Django 4.2.9 on 2024-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0032_rename_date_vente_vente_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='retour',
            name='motif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
