# Generated by Django 4.2.9 on 2024-10-08 17:09

import avoirapp.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0033_retour_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='date_renvoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='avoir',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to=avoirapp.models.upload_invoice_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='retour',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to=avoirapp.models.upload_invoice_path_retour, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
