# Generated by Django 4.2.9 on 2024-10-08 17:14

import avoirapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0035_alter_avoir_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avoir',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to=avoirapp.models.upload_invoice_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
