# Generated by Django 4.2.9 on 2024-10-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0037_retour_date_renvoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enfants_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom'), name='unique_nom_prenom'),
        ),
    ]
