# Generated by Django 4.2.9 on 2024-10-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0039_remove_client_unique_nom_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoir',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consommation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
