# Generated by Django 4.2.9 on 2024-10-14 14:16

import avoirapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirapp', '0040_avoir_is_confirmed_consommation_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enfants',
            field=models.ManyToManyField(blank=True, related_name='parents', to='avoirapp.client'),
        ),
        migrations.AlterField(
            model_name='avoir',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to=avoirapp.models.upload_invoice_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
